spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/issuetalk

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

ai:
  provider: openai

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

openai:
  api-key: ${OPENAI_API_KEY}
  model: gpt-3.5-turbo
  api:
    url: https://api.openai.com/v1/chat/completions

news:
  api:
    key: ${NEWS_API_KEY}
