server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb+srv://issuetalk:12345678@cluster0.ht1f3xk.mongodb.net/issuetalk?retryWrites=true&w=majority&appName=Cluster0

logging:
  level:
    root: INFO

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

ai:
  provider: openai

openai:
  api-key: ${OPENAI_API_KEY}
  model: gpt-3.5-turbo
  api:
    url: https://api.openai.com/v1/chat/completions
